package com.latbc.dataviz.swing.ui;

/**
*
* @author 
*/
public class DBSelection extends javax.swing.JFrame {

   /**
    * Creates new form DBSelection
    */
   public DBSelection() {
       initComponents();
       
       dataBaseGroupSelection.add(oracleOption);
       dataBaseGroupSelection.add(mysqlOption);
       dataBaseGroupSelection.add(sqlServer);
       
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       dataBaseGroupSelection = new javax.swing.ButtonGroup();
       dbSelectionHeadTitle = new javax.swing.JLabel();
       oracleOption = new javax.swing.JRadioButton();
       mysqlOption = new javax.swing.JRadioButton();
       sqlServer = new javax.swing.JRadioButton();
       connectBtnDB = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       dbSelectionHeadTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
       dbSelectionHeadTitle.setText("SELECT DATA BASE");

       oracleOption.setText("ORACLE");
       oracleOption.setToolTipText("");

       mysqlOption.setText("MySQL");

       sqlServer.setText("SQL Server");

       connectBtnDB.setText("Connect");
       connectBtnDB.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               connectBtnDBMouseClicked(evt);
           }
       });
       connectBtnDB.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               connectBtnDBActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(connectBtnDB)
               .addGap(48, 48, 48))
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(37, 37, 37)
                       .addComponent(dbSelectionHeadTitle))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(89, 89, 89)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(sqlServer)
                           .addComponent(mysqlOption)
                           .addComponent(oracleOption))))
               .addContainerGap(188, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(33, 33, 33)
               .addComponent(dbSelectionHeadTitle)
               .addGap(33, 33, 33)
               .addComponent(oracleOption)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(mysqlOption)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(sqlServer)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
               .addComponent(connectBtnDB)
               .addGap(33, 33, 33))
       );

       pack();
   }// </editor-fold>                        

   private void connectBtnDBActionPerformed(java.awt.event.ActionEvent evt) {                                             
       
   }                                            

   private void connectBtnDBMouseClicked(java.awt.event.MouseEvent evt) {                                          
//       RunQuery runQuery = new RunQuery();
//       runQuery.setVisible(true);
//       this.dispose();
       
       PantallaConexion pm = new PantallaConexion();
       pm.setVisible(true);
       this.dispose();
       
    
   }                                         

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(DBSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(DBSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(DBSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(DBSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new DBSelection().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton connectBtnDB;
   private javax.swing.ButtonGroup dataBaseGroupSelection;
   private javax.swing.JLabel dbSelectionHeadTitle;
   private javax.swing.JRadioButton mysqlOption;
   private javax.swing.JRadioButton oracleOption;
   private javax.swing.JRadioButton sqlServer;
   // End of variables declaration                   
}
