package com.latbc.dataviz.swing.ui;

import java.sql.SQLException;

import com.latbc.dataviz.exceptions.DatabaseConnectionException;
import com.latbc.dataviz.mysql.dao.impl.ClientRentsDAOImpl;

/**
 *
 * @author Latbc
 */
public class RunQuery extends javax.swing.JFrame {

    /**
     * Creates new form RunQuery
     */
    public RunQuery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        rentByIdClient = new javax.swing.JLabel();
        idVariable = new javax.swing.JLabel();
        fieldIdClientVariable = new javax.swing.JTextField();
        idVariableCreateJsonBtn = new javax.swing.JButton();
        titleFrameCreateJSON = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rentByIdClient.setText("Rent By ID Client");

        idVariable.setText("ID Client:");

        fieldIdClientVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdClientVariableActionPerformed(evt);
            }
        });

        idVariableCreateJsonBtn.setText("Create JSON file");
        idVariableCreateJsonBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idVariableCreateJsonBtnMouseClicked(evt);
            }
        });
        idVariableCreateJsonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idVariableCreateJsonBtnActionPerformed(evt);
            }
        });

        titleFrameCreateJSON.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleFrameCreateJSON.setText("Execute Query to create JSON File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(idVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldIdClientVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleFrameCreateJSON)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(idVariableCreateJsonBtn)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rentByIdClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titleFrameCreateJSON)
                .addGap(88, 88, 88)
                .addComponent(rentByIdClient)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idVariableCreateJsonBtn)
                    .addComponent(fieldIdClientVariable)
                    .addComponent(idVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void fieldIdClientVariableActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        
        
        
    }                                                     

    private void idVariableCreateJsonBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        
        fieldIdClientVariable.getText();
        
    }                                                       

    private void idVariableCreateJsonBtnMouseClicked(java.awt.event.MouseEvent evt) {                                                     
        
    	ClientRentsDAOImpl clienteRentas = new ClientRentsDAOImpl();
    	try {
    		
			clienteRentas.getRentsByCustomerId(fieldIdClientVariable.getText());
//		} catch (InstantiationException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		} catch (IllegalAccessException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		} catch (ClassNotFoundException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		} catch (FileNotFoundException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (DatabaseConnectionException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
    }                                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunQuery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField fieldIdClientVariable;
    private javax.swing.JLabel idVariable;
    private javax.swing.JButton idVariableCreateJsonBtn;
    private javax.swing.JLabel rentByIdClient;
    private javax.swing.JLabel titleFrameCreateJSON;
    // End of variables declaration                   
}