package com.latbc.dataviz.swing.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class SelectionMenu extends javax.swing.JFrame {

    /**
     * Creates new form MenuSeleccion
     */
    public SelectionMenu() {
        initComponents();
        
        //Agreagr opciones fuentes de datos
        dataSourceGroup.add(optionExcel);
        dataSourceGroup.add(opctionBD);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        dataSourceGroup = new javax.swing.ButtonGroup();
        dbDataVizMenuHeadTitle = new javax.swing.JLabel();
        optionExcel = new javax.swing.JRadioButton();
        opctionBD = new javax.swing.JRadioButton();
        buttonNext = new javax.swing.JButton();
        dataSourceOptionsTitle = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dbDataVizMenuHeadTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        dbDataVizMenuHeadTitle.setText("DATA VIZ MENU");

        optionExcel.setText("Excel");

        opctionBD.setText("Data Base");
        opctionBD.setToolTipText("");
        opctionBD.setActionCommand("DataBase");
        opctionBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opctionBDActionPerformed(evt);
            }
        });

        buttonNext.setText("Next");
        buttonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNextMouseClicked(evt);
            }
        });

        dataSourceOptionsTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dataSourceOptionsTitle.setText("Data Source Options:");

        jMenu1.setText("DataViz");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Salir");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonNext)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opctionBD)
                            .addComponent(optionExcel)
                            .addComponent(dataSourceOptionsTitle))
                        .addGap(112, 112, 112))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(dbDataVizMenuHeadTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(dbDataVizMenuHeadTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(dataSourceOptionsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionExcel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opctionBD)
                .addGap(18, 18, 18)
                .addComponent(buttonNext)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        System.exit(1);
    }                                                     

    private void buttonNextMouseClicked(java.awt.event.MouseEvent evt) {                                        
        
        //Por prueba solo se mostrara mensaje, la accion debera enviar a la pantalla de la fuente de datos seleccionada
        String mensaje = "";
        
        if(optionExcel.isSelected()){
            mensaje = "Extraer de Excel"; //Hacia 
        } else if (opctionBD.isSelected()){
            DBSelection dbSelection = new DBSelection();
            dbSelection.setVisible(true);
            this.dispose();
        } else {
            mensaje = "Seleccionar una fuente de Datos";
            JOptionPane.showMessageDialog(null, mensaje);
        }
    }                                       

    private void opctionBDActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectionMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonNext;
    private javax.swing.ButtonGroup dataSourceGroup;
    private javax.swing.JLabel dataSourceOptionsTitle;
    private javax.swing.JLabel dbDataVizMenuHeadTitle;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButton opctionBD;
    private javax.swing.JRadioButton optionExcel;
    // End of variables declaration                   
}
